webservices:
    github:
        host: https://api.github.com
        services:
            users: ${webservices.github.host}/users
            repos: ${webservices.github.host}/repos
    gitlab:
        host: https://gitlab.com/api/v4
        services:
            users: ${webservices.gitlab.host}/users
            projects: ${webservices.gitlab.host}/projects