spring:
    mvc:
        throw-exception-if-no-handler-found: true
        pathmatch:
            matching-strategy: ant_path_matcher
    resources:
        add-mappings: false
    main:
        banner-mode: 'OFF'
    jackson:
        serialization:
            write_dates_as_timestamps: false

webservices:
    github:
        host: https://api.github.com
        services:
            users: ${webservices.github.host}/users
            repos: ${webservices.github.host}/repos
    gitlab:
        host: https://gitlab.com/api/v4
        services:
            users: ${webservices.gitlab.host}/users
            projects: ${webservices.gitlab.host}/projects
